services:
  openvpn:
    image: kylemanna/openvpn
    network_mode: host
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    volumes:
      - ./ovpn-data:/etc/openvpn
    restart: unless-stopped
    env_file:
      - ./.env
    devices:
      - /dev/net/tun:/dev/net/tun
    healthcheck:
      test: ["CMD-SHELL", "ps | grep -q '[o]penvpn'"]
      interval: 30s
      timeout: 5s
      retries: 3
